#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "7y5NA/Azb90E"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60



#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD